"""Created urlmodels table

Revision ID: 53e2db901362
Revises:
Create Date: 2025-11-11 10:39:25.250811

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "53e2db901362"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urlmodels",
        sa.Column(
            "original_url", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "shortened_code", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("clicks", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("urlmodels_pkey")),
    )
    op.create_index(
        op.f("ix_urlmodels_shortened_code"),
        "urlmodels",
        ["shortened_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_urlmodels_original_url"),
        "urlmodels",
        ["original_url"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_urlmodels_original_url"), table_name="urlmodels")
    op.drop_index(op.f("ix_urlmodels_shortened_code"), table_name="urlmodels")
    op.drop_table("urlmodels")
    # ### end Alembic commands ###
